name: fraud_protection
description: "Plugin to monitor and prevent fraud attempts and malicious services to interact with your app. Contribute to list of blacklisted apps to keep everyone safe."
version: 1.0.1
homepage: https://github.com/RelappsStudio/fraud_protection
repository: https://github.com/RelappsStudio/fraud_protection.git
issue_tracker: https://github.com/RelappsStudio/fraud_protection/issues

environment:
  sdk: ">=2.17.0 <4.0.0"
  flutter: ">=1.20.0"

dependencies:
  flutter:
    sdk: flutter
  plugin_platform_interface: ^2.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.relapps.fraud_protection
        pluginClass: FraudProtectionPlugin
